### ISSUE TITLE
missing "'em" from leftovers_dict

### ISSUE THREAD

**Issue by bios-killer** [kootenpv/contractions#1]
leftovers_dict is missing "'em": " them", line
(thank you for your work!..)

**Comment by kootenpv** [comment]
Thanks for reporting!

I added `'em`. It is available on pip since `contractions==0.0.12`.

Remember that to upgrade you should use `pip install -U --no-cache contractions`

**Comment by bios-killer** [comment]
Great! Thank you for your lightning-fast response!06.03.2017, 00:18, "Pascal van Kooten" <notifications@github.com>:Thanks for reporting!
I added 'em. It is available on pip since contractions==0.0.12.
Remember that to upgrade you should use pip install -U --no-cache contractions

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Regards,Roman Ilienkov
