### ISSUE TITLE
Capitalization not preserved

### ISSUE THREAD

**Issue by plusuncold** [kootenpv/contractions#16]
It would be helpful to preserve capitalization in the cases where a word like 'you' is at the start of a sentence. For example

```
    >>> import contractions
    >>> phrase = "You'll need this."
    >>> contractions.fix(phrase)
    "you will need this."
```

**Comment by ashutosh486** [comment]
For a workaround solution, I am using symspellpy module (used for spell checker).
`from symspellpy import helpers`
`orig_text = "You'll need this."`
`expanded_text = helpers.transfer_casing_for_similar_text(orig_text, contractions.fix(orig_text))`
`print("Original Text: {} \nModified Text: {}".format(orig_text, expanded_text))`

Output:
_Original Text: You'll need this. 
Modified Text: You will need this._

**Comment by nickumia** [comment]
@plusuncold @ashutosh486 I accidentally duplicated this issue (#43) and we got a workaround merged, so no additional processing is needed anymore 👍 (#44)

@kootenpv I think it's safe to close this issue.

**Comment by kootenpv** [comment]
@nickumia Awesome, yea agree!
