### ISSUE TITLE
Introduction of GitHub Actions

### ISSUE THREAD

**Issue by daikikatsuragawa** [kootenpv/contractions#22]
I think it is a good idea to run automated unit tests at a commit time.

**Comment by kootenpv** [comment]
Yea definitely, I can add Travis CI for this as I have set up that earlier for similar projects: https://travis-ci.org/github/kootenpv

Would Travis be good here too?

**Comment by daikikatsuragawa** [comment]
If you can use Travis CI, there should be no problem.
The issue here is closing!
