### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sajal2692** [kootenpv/contractions#28]
Hi

I see that the license for this repository, as set in `setup.py` is `MIT`. 
Can we also add a LICENSE file to the repo? 

Thanks!

**Comment by kootenpv** [comment]
Sure! Feel free to make a PR

**Comment by sajal2692** [comment]
Done: https://github.com/kootenpv/contractions/pull/29

**Comment by kootenpv** [comment]
Indeed, thanks!

**Comment by sajal2692** [comment]
Hi

I just figured out that we ended up adding the wrong LICENSE here. As this package uses `textsearch`, which in turn uses `Unidecode` - with a GPL license. This package must also have a GPL license, by effect of GPL's strong copyleft requirements.

**Comment by kootenpv** [comment]
> Hi
> 
> I just figured out that we ended up adding the wrong LICENSE here. As this package uses `textsearch`, which in turn uses `Unidecode` - with a GPL license. This package must also have a GPL license, by effect of GPL's strong copyleft requirements.

As discussed on `textsearch`, we will handle it there :)
