### ISSUE TITLE
"Can't" shouldn't resolve to "can not"

### ISSUE THREAD

**Issue by Kev-Y-Huang** [kootenpv/contractions#35]
Can't is a [contraction](https://www.grammarly.com/blog/cannot-or-can-not/) of cannot. Would just need to change these [two occurrences](https://github.com/kootenpv/contractions/blob/d80ed47e22e0617503229e92383dc4ed69fb389c/contractions/data/contractions_dict.json#L15-L16) I believe.

Very particular, but just noticed while playing around.

**Comment by kootenpv** [comment]
> Can't is a [contraction](https://www.grammarly.com/blog/cannot-or-can-not/) of cannot. Would just need to change these [two occurrences](https://github.com/kootenpv/contractions/blob/d80ed47e22e0617503229e92383dc4ed69fb389c/contractions/data/contractions_dict.json#L15-L16) I believe.
> 
> Very particular, but just noticed while playing around.

Wow, good catch! Feel free to make a PR if you want, it looks correct!

**Comment by Kev-Y-Huang** [comment]
#36 Just created a PR to fix!

**Comment by kootenpv** [comment]
You can get the new version using

    pip install -U --no-cache contractions>=0.0.52
