### ISSUE TITLE
Contractions module does not expand "I'm" to "I am"

### ISSUE THREAD

**Issue by Landrow** [kootenpv/contractions#4]
Hi, I tried the contractions module and it does not expand "I'm to "I am". Have anyone encountered this?

**Comment by kootenpv** [comment]
FYI noticed it doesn't work with lower case

**Comment by Landrow** [comment]
Yes, it does not work with lower case. Will a later version resolve the issue? Thank you.

**Comment by kootenpv** [comment]
Not sure when it got fixed, but it is fixed in at least `contractions>=0.0.23`
