### ISSUE TITLE
Ignore vs. Insensitive

### ISSUE THREAD

**Issue by nickumia** [kootenpv/contractions#43]
Hi,

I noticed that all of the `TextSearch` classes are initialized with ["ignore"](https://github.com/kootenpv/textsearch/blob/master/textsearch/__init__.py#L74-L75) instead of ["insensitive"](https://github.com/kootenpv/textsearch/blob/master/textsearch/__init__.py#L76-L77) ([Example](https://github.com/kootenpv/contractions/blob/master/contractions/__init__.py#L75)).

Is that the intended behavior?  

I originally wrote a test to verify that this library was doing what I expected it to,
```
    def test_semi_sanitize():
>       assert contractions.fix("What're they going to do about the PIZZA?!") == \
                "What are they going to do about the PIZZA?!"
E       AssertionError: assert 'what are the...t the PIZZA?!' == 'What are the...t the PIZZA?!'
E         - What are they going to do about the PIZZA?!
E         ? ^
E         + what are they going to do about the PIZZA?!
E         ? ^
```

Do you think it would be more appropriate to change it to "insensitive" for cases like the above?

**Comment by kootenpv** [comment]
Great catch 👌nice digging... Please make a PR :)

**Comment by nickumia** [comment]
PR Incoming... would you mind some github actions for linting and running pytests?
