### ISSUE TITLE
"cause" --> "because" is not always valid

### ISSUE THREAD

**Issue by heatxg** [kootenpv/contractions#45]
Instances of "cause" are converted to "because". This is not always relevant.  
  
Ex:
```
text = "The coming storm is likely to cause a lot of damage"
contractions.fix(text)
```
Output:   
"The coming storm is likely to because a lot of damage."  
  
--------
This replacement is in `leftovers_dict.json` but is still applied with `leftovers=False` unless `slang=False` as well.   
  
Ex:
```
text = "The coming storm is likely to cause a lot of damage"
contractions.fix(text, leftovers=False)
```
Output:   
"The coming storm is likely to because a lot of damage."  
  
Ex:
```
text = "The coming storm is likely to cause a lot of damage"
contractions.fix(text, leftovers=False, slang=False)
```
Output:   
"The coming storm is likely to cause a lot of damage."

**Comment by kootenpv** [comment]
Thanks for filing the issue!

Maybe we can specifically add `to cause` to be replaced with `to cause` to prevent it from being changed.
