### ISSUE TITLE
PyPI version off-by-one

### ISSUE THREAD

**Issue by PaddyAlton** [kootenpv/contractions#8]
Hi, just a small one :) I got a notification that PyPI had a new version of the package (v0.0.18), but when I looked at what was in the diff I saw that the version in setup.py is off by one. Probably you just started at 0.0.0 or something. 

Might be worth incrementing the `MICRO_VERSION` by two next time you release to PyPI so the version numbering is consistent?

**Comment by kootenpv** [comment]
Thanks for mentioning it. My deploying schedule is a bit odd... it depends on the commit count. It is monotonically increasing, but not very predictable.
