### ISSUE TITLE
'textsearch' should be listed as a dependency 

### ISSUE THREAD

**Issue by theMogget** [kootenpv/contractions#9]
Tried to import the class and got the following error:

```
~/python-environments/base/lib/python3.7/site-packages/contractions/__init__.py in <module>
----> 1 from textsearch import TextSearch
      2 
      3 
      4 contractions_dict = {
      5     "ain't": "are not",

ModuleNotFoundError: No module named 'textsearch'
```

Easily solved with `pip install textsearch`, but saves people a few clicks through your other repos. ;)

**Comment by kootenpv** [comment]
Sorry for missing this for so long, but it's merged now.

`pip install contractions>=0.0.23`
